onEvent('recipes', event => {
    event.remove({id:'mekanism:pigment_extracting/stained_glass_pane/blue'})
    event.remove({id:'mekanism:pigment_extracting/terracotta/blue'})
    event.remove({id:'mekanism:pigment_extracting/wool/blue'})
    event.remove({id:'mekanism:pigment_extracting/carpet/blue'})
    event.remove({id:'mekanism:pigment_extracting/dye/blue'})
    event.remove({id:'mekanism:pigment_extracting/concrete/blue'})
    event.remove({id:'mekanism:pigment_extracting/banner/blue'})
    event.remove({id:'mekanism:pigment_extracting/concrete_powder/blue'})
    event.remove({id:'mekanism:pigment_extracting/stained_glass/blue'})
    event.remove({id:'mekanism:pigment_extracting/candle/blue'})
    event.remove({id:'mekanism:pigment_extracting/flower/blue'})
})